[package]
name = "tapestry-loom"
version = "0.14.0"
authors = [
	"transkatgirl",
]
homepage = "https://github.com/transkatgirl/Tapestry-Loom"
license = "AGPL-3.0-or-later"
description = "A power user focused interface for LLM base models."
edition = "2024"

[package.metadata]
donate = "https://github.com/sponsors/transkatgirl"

[features]
donation-link = [  ]
#inspection = [
#	"eframe/inspection",
#]

[dependencies] # TODO: Cleanup & update dependencies
tapestry-weave = { path = "tapestry-weave", features = [
	"v0",
], default-features = false }
eframe = { version = "0.36.2", features = [ # egui 0.35.0 has a serious performance regression - likely https://github.com/emilk/egui/issues/8610
	"accesskit",
	"wayland",
	#"web_screen_reader",
	"wgpu",
	"x11",
	"persistence",
], default-features = false }
env_logger = { version = "0.11.11", features = [
	"auto-color",
	"humantime",
] }
log = { version = "0.4.34", features = [
	"release_max_level_debug",
] }
mimalloc = "0.1.52"
serde = { version = "1.0.229", features = [
	"derive",
	"rc",
] }
serde_json = { version = "1.0.151", features = [
	"preserve_order",
	"float_roundtrip",
	"arbitrary_precision",
] }
ron = { version = "0.12.2", features = [
	"indexmap",
	"integer128",
	"unicode-segmentation",
] }
reqwest = { version = "0.13.5", features = [
	"json",
	"gzip",
	"brotli",
	"zstd",
	"deflate",
] }
parking_lot = { version = "0.12.5", features = [
	"serde",
] }
anyhow = "1.0.104"
dirs-next = "2.0.0"
egui_tiles = "0.17.1"
egui-notify = "0.23.0"
tokio = { version = "1.53.1", features = [
	"full",
] }
futures = "0.3.34"
walkdir = "2.5.0"
unicode-segmentation = "1.13.3"
trash = "5.2.9"
ctrlc = "3.5.2"
egui-keybind = { git = "https://github.com/transkatgirl/egui-keybind.git", rev = "8ff2975f8575ed216528e84e016741afcd346bea", features = [
	"serde",
] }
flagset = { version = "0.4.7", features = [
	"std",
] }
bytes = "1.12.1"
ml-distance = "1.0.1"
elkai-rs = "0.1.7"
base64 = "0.23.1"
linked-hash-map = "0.5.6"
ulid = { version = "3.0.0", features = [
	"serde",
] }
lexical-sort = { git = "https://github.com/transkatgirl/lexicmp.git", rev = "4d5457eebb9e6a7f2ee56a25fc2528d88f2bb4c3" }
color = { version = "0.3.3", features = [
	"serde",
] }

[build-dependencies]
cargo_metadata = "0.23.1"

[profile.dev]
opt-level = 3

[profile.release]
lto           = "thin"
codegen-units = 1
strip         = "symbols"
panic         = "abort"

[workspace]
members = [
	"tapestry-weave",
	"migration-assistant",
	"tapestry-tokenize",
]
