[package]
name = "tapestry-loom-migration-assistant"
version = "0.5.0"
authors = [
	"transkatgirl",
]
homepage = "https://github.com/transkatgirl/Tapestry-Loom"
license = "Unlicense"
description = "A tool for converting weaves from other Loom implementations into the Tapestry Loom weave format."
edition = "2024"

[dependencies]
base64 = "0.22.1"
miniz_oxide = { version = "0.9.1", features = [
	"std",
] }
frontmatter = "0.4.0"
boa_engine = { version = "0.21.1", default-features = false }
tapestry-weave = { path = "../tapestry-weave", features = [
	"all_versions",
	"serde",
] }
clap = { version = "4.6.1", features = [
	"derive",
] }
anyhow = "1.0.103"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = [
	"derive",
] }
serde_json = { version = "1.0.150", features = [
	"preserve_order",
	"float_roundtrip",
] }
chrono = { version = "0.4.45", features = [
	"alloc",
	"std",
	"clock",
	"serde",
], default-features = false }
uuid = { version = "1.23.4", features = [
	"serde",
], default-features = false }
