[package]
name = "tapestry-loom-migration-assistant"
version = "0.4.1"
authors = [
	"transkatgirl",
]
homepage = "https://github.com/transkatgirl/Tapestry-Loom"
license = "Unlicense"
description = "A tool for converting weaves from other Loom implementations into the Tapestry Loom weave format."
edition = "2024"

[dependencies] # TODO: Review dependencies
base64 = "0.22.1"
miniz_oxide = "0.9.1"
frontmatter = "0.4.0"
boa_engine = "0.21.1"
tapestry-weave = { path = "../tapestry-weave", features = [
	"all_versions",
	"serde",
] }
clap = { version = "4.6.1", features = [
	"derive",
] }
anyhow = "1.0.102"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = [
	"derive",
	"rc",
] }
serde_json = { version = "1.0.150", features = [
	"preserve_order",
	"arbitrary_precision",
] }
uuid = { version = "1.23.3", features = [
	"serde",
] }
