[package]
name = "tapestry-polyclient"
version = "0.0.0"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "An implementation of Tapestry Loom's LLM inference client."
edition = "2024"

[features]
weave = [ # tapestry-weave integration
	"dep:tapestry-weave",
]

[dependencies]
serde = { version = "1.0.228", features = [
	"derive",
] }
serde_json = { version = "1.0.150", features = [
	"preserve_order",
	"float_roundtrip",
] }
chrono = { version = "0.4.45", features = [
	"alloc",
	"std",
	"clock",
	"serde",
], default-features = false }
ulid = "1.2.1"

# weave
tapestry-weave = { path = "../tapestry-weave", optional = true }
