[package]
name = "tapestry-weave"
version = "0.0.0"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "An implementation of Tapestry Loom's document format."
edition = "2024"

[features]
default = [ "v0" ]
all_versions = [
	"v0",
]
v0 = [
	"universal-weave/legacy",
	"dep:ulid",
	"dep:chrono",
]

[dependencies]
rkyv = { version = "0.8.18", features = [
	"little_endian",
	"aligned",
	"pointer_width_32",
	"indexmap-2",
] }
universal-weave = { version = "0.8.1", features = [
	"serde",
] }
foldhash = "0.2.0"
jiff = { version = "0.2.35", features = [
	"serde",
] }
nanorand = { version = "0.8.0", features = [
	"alloc",
	"wyrand",
	"getrandom",
], default-features = false }
serde = { version = "1.0.229", features = [
	"derive",
	"rc",
] }
serde_json = { version = "1.0.151", features = [
	"preserve_order",
	"float_roundtrip",
] }
base64 = "0.23.1"
base64-serde = "0.8.0"

# v0
ulid = { version = "3.0.0", features = [
	"serde",
], optional = true }
chrono = { version = "0.4.45", features = [
	"alloc",
	"std",
], default-features = false, optional = true }
