[package]
name = "tapestry-weave"
version = "0.0.0"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "An implementation of Tapestry Loom's document format."
edition = "2024"

[features]
default = [ "v0" ]
all_versions = [
	"v0",
]
v0 = [
	"universal-weave/legacy",
	"universal-weave/serde",
	"dep:ulid",
	"dep:serde_json",
	"dep:base64",
	"dep:chrono",
]
serde = [ # serde integration
	"universal-weave/serde",
	"jiff/serde",
	"dep:serde",
	"dep:base64",
	"dep:base64-serde",
]

[dependencies]
contracts = "0.6.7"
rkyv = { version = "0.8.16", features = [
	"little_endian",
	"aligned",
	"pointer_width_32",
	"indexmap-2",
] }
universal-weave = "0.2.0"
foldhash = "0.2.0"
jiff = "0.2.29"
nanorand = { version = "0.8.0", features = [
	"alloc",
	"wyrand",
	"getrandom",
], default-features = false }

# serde
serde = { version = "1.0.228", optional = true, features = [
	"derive",
	"rc",
] }
base64 = { version = "0.22.1", optional = true } # also used by v0
base64-serde = { version = "0.8.0", optional = true }

# v0
ulid = { version = "1.2.1", features = [
	"serde",
], optional = true }
serde_json = { version = "1.0.150", features = [
	"preserve_order",
	"float_roundtrip",
], optional = true }
chrono = { version = "0.4.45", features = [
	"alloc",
	"std",
], default-features = false, optional = true }
